language: php
php:
- 5.5
- 7.0
- hhvm
# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
script: phpunit test


