language: php
php:
    - "5.3"
    - "5.4"
    - "5.5"
    - "5.6"
    - "7.0"
    - "nightly"

sudo: false

install:
    - travis_retry composer self-update && composer --version
    - travis_retry composer install --prefer-dist --dev
