language: php

php:
  - 5.6
  - hhvm

env:
  global:
    - setup=basic

matrix:
  include:
    - php: 5.6
      env: setup=lowest
    - php: 5.6
      env: setup=stable

sudo: false

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-lowest --prefer-stable; fi

script: vendor/bin/phpunit test
services:
  - mysql
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -e 'create database IF NOT EXISTS platziphp;'
  - mysql -e 'use platziphp;'
  - mysql -e 
  	'CREATE TABLE `posts` (
  `id` int(100) NOT NULL,
  `author_id` int(100) NOT NULL,
  `title` varchar(100) NOT NULL,
  `body` varchar(100) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;
  	INSERT INTO `posts` (`id`, `author_id`, `title`, `body`) VALUES
(1, 1, 'primer post', 'contenido del primer post'),
(2, 2, 'segundo post', 'contenido del segundo post'),
(3, 3, 'tercer post', 'contenido del tercer post'),
(4, 4, 'cuarto post', 'contenido del cuarto post');
	CREATE TABLE `users` (
  `id` int(100) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(50) NOT NULL,
  `first_name` varchar(50) NOT NULL,
  `last_name` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
	INSERT INTO `users` (`id`, `email`, `password`, `first_name`, `last_name`) VALUES
(1, 'jhonny@gmail.com', '1234', 'jhonny', 'arana'),
(2, 'leonardo@gmail.com', '1234', 'leonardo', 'aguilar'),
(3, 'xiomara@gmail.com', 'verano', 'xiomara', 'nieves'),
(4, 'foo', 'car', 'foo', 'bar');'
